// ================= DICTIONARY PAGE =================
function renderDictionary() {
    const dictionary = JSON.parse(localStorage.getItem('sipSpeakDictionary') || '[]');
    const mainContent = document.getElementById('mainContent');
    
    if (dictionary.length === 0) {
        mainContent.innerHTML = `
            <span class="emoji">📚</span>
            <h2>My Personal Dictionary</h2>
            <p style="text-align: center; color: var(--text-secondary); margin-top: 20px;">
                Your dictionary is empty. Go to lessons and click ⭐ on words to add them here!
            </p>
        `;
        return;
    }
    
    let cardsHtml = dictionary.map((item, index) => `
        <div class="flip-card" style="height: auto; min-height: 180px;">
            <div class="flip-card-inner" style="transform: none;">
                <div class="flip-card-front" style="position: relative; padding: 20px;">
                    <button class="audio-btn" onclick="speakText('${item.word}')" title="Listen" style="right: 50px; top: 10px;"></button>
                    <button class="audio-btn" onclick="removeFromDictionary(${index})" title="Remove" style="right: 10px; top: 10px; background: #ff6b6b; border-color: #ff6b6b;">✕</button>
                    <span class="front-word">${item.word}</span>
                    <p class="back-def" style="margin-top: 15px;">${item.definition}</p>
                    <p class="back-example">"${item.example}"</p>
                </div>
            </div>
        </div>
    `).join('');
    
    mainContent.innerHTML = `
        <span class="emoji"></span>
        <h2>My Personal Dictionary</h2>
        <p style="text-align: center; color: var(--text-secondary); margin-bottom: 20px;">
            ${dictionary.length} word${dictionary.length > 1 ? 's' : ''} saved
        </p>
        <div class="mt-20">${cardsHtml}</div>
    `;
}

function removeFromDictionary(index) {
    let dictionary = JSON.parse(localStorage.getItem('sipSpeakDictionary') || '[]');
    const removed = dictionary.splice(index, 1)[0];
    localStorage.setItem('sipSpeakDictionary', JSON.stringify(dictionary));
    renderDictionary();
    showNotification(`"${removed.word}" removed from dictionary`);
}

function clearDictionary() {
    if (confirm('Are you sure you want to clear your entire dictionary?')) {
        localStorage.removeItem('sipSpeakDictionary');
        renderDictionary();
        showNotification('Dictionary cleared');
    }
}

function exportDictionary() {
    const dictionary = JSON.parse(localStorage.getItem('sipSpeakDictionary') || '[]');
    
    if (dictionary.length === 0) {
        alert('Your dictionary is empty!');
        return;
    }
    
    const html = `
        <div style="font-family: Arial, sans-serif; padding: 30px; color: #333;">
            <h1 style="color: #76845B; text-align: center; border-bottom: 2px solid #76845B; padding-bottom: 10px;">
                📚 My Personal Dictionary
            </h1>
            <p style="text-align: center; color: #666; font-style: italic;">Sip & Speak</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 30px;">
                <tr style="background: #f4f4f4;">
                    <th style="padding: 12px; text-align: left; border: 1px solid #ddd;">Word</th>
                    <th style="padding: 12px; text-align: left; border: 1px solid #ddd;">Definition</th>
                    <th style="padding: 12px; text-align: left; border: 1px solid #ddd;">Example</th>
                </tr>
                ${dictionary.map(item => `
                    <tr>
                        <td style="padding: 12px; border: 1px solid #ddd; font-weight: bold; color: #76845B;">${item.word}</td>
                        <td style="padding: 12px; border: 1px solid #ddd;">${item.definition}</td>
                        <td style="padding: 12px; border: 1px solid #ddd; font-style: italic; color: #666;">"${item.example}"</td>
                    </tr>
                `).join('')}
            </table>
            
            <p style="text-align: center; margin-top: 40px; font-size: 0.8rem; color: #999;">
                Generated by Sip & Speak App
            </p>
        </div>
    `;
    
    const opt = {
        margin: 10,
        filename: 'My_Personal_Dictionary.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    
    html2pdf().set(opt).from(html).save();
}

function showNotification(message) {
    const notification = document.createElement('div');
    notification.style.cssText = `
        position: fixed; bottom: 30px; left: 50%; transform: translateX(-50%);
        background: #76845B; color: white; padding: 15px 30px;
        border-radius: 50px; box-shadow: 0 4px 20px rgba(0,0,0,0.2);
        z-index: 10000; font-family: 'Poppins', sans-serif; font-size: 0.95rem;
    `;
    notification.textContent = message;
    document.body.appendChild(notification);
    
    setTimeout(() => notification.remove(), 2000);
}

function speakText(text) {
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = 'en-GB';
    utterance.rate = 0.9;
    window.speechSynthesis.speak(utterance);
}

// Initialize
document.addEventListener('DOMContentLoaded', renderDictionary);